version: "3"

services: 
    rest:
        image: "traffic-controller"
        volumes:
            - "./rest-api-mongo/:/rest-api"
        ports: 
            - 80:80
    db:
        image: "mongo:4.0.5"
        ports:
        - 27017:27017
        container_name: db
        restart: always
        environment: 
            MONGO_INITDB_DATABASE: trafficlights
    # ngrok: