version: "3"

services: 
    rest:
        image: "traffic-controller"
        volumes:
            - './rest-api-mongo/:/rest-api'
        ports: 
            - 80:80
        container_name: rest
        environment:
            - CHOKIDAR_USEPOLLING=true
    db:
        image: "mongo:4.0.5"
        ports:
            - 27017:27017
        container_name: db
        restart: always
        environment: 
            MONGO_INITDB_DATABASE: trafficlights
    ngrok:
        image: wernight/ngrok
        container_name: ngrok
        ports:
            - 4040:4040
        links:
            - rest
        environment:
            - NGROK_PORT=rest:80
    cube:
        image: cubejs
        volumes: 
            - './mongo-dashboard/real-time-dashboard:/real-time-dashboard'
            - '/real-time-dashboard/node_modules'
            - './mongo-dashboard/dashboard-app:/real-time-dashboard/dashboard-app'
            - '/real-time-dashboard/dashboard-app/node_modules'
            - './mongo-dashboard/:/output'
            - './history.json:/history.json'
            - './mongo-dashboard/start-cube.sh:/start-cube.sh'
            - ./events-dump:/events-dump
        ports:
            - 3000:3000
            - 4000:4000
        working_dir: /
        container_name: cube
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - db
    cube_db:
        image: "mongobi"
        ports:
            - 3307:3307
        volumes: 
            - "./mongo-dashboard/mongosqld/mongosqld.conf:/mongosqld.conf"
        restart: always
        depends_on: 
            - cube
        container_name: cube_db
